# Generated by Django 2.0.6 on 2018-06-27 12:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dostbook', '0002_friend'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='friend',
            new_name='friends',
        ),
    ]
