# Generated by Django 2.0.6 on 2018-06-28 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dostbook', '0003_auto_20180627_1215'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='name',
            field=models.CharField(default='SOME STRING', max_length=50),
        ),
    ]
