# Generated by Django 2.0.6 on 2018-07-04 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dostbook', '0005_auto_20180629_1745'),
    ]

    operations = [
        migrations.CreateModel(
            name='post',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('msg', models.CharField(max_length=500)),
                ('sender', models.CharField(max_length=50)),
            ],
        ),
    ]
