# Generated by Django 2.0.6 on 2018-07-05 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dostbook', '0006_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='state',
            field=models.CharField(default='SOME STRING', max_length=50),
        ),
    ]
