# Generated by Django 2.0.6 on 2018-07-05 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dostbook', '0007_student_state'),
    ]

    operations = [
        migrations.CreateModel(
            name='profpic',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=50)),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='profile_picture/%y%m%d')),
            ],
        ),
    ]
