# Generated by Django 2.0.6 on 2018-07-05 17:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dostbook', '0008_profpic'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profpic',
            old_name='email',
            new_name='emailid',
        ),
    ]
