# Generated by Django 2.0.6 on 2018-07-05 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dostbook', '0009_auto_20180705_1753'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profpic',
            name='emailid',
            field=models.CharField(default='SOME STRING', max_length=50),
        ),
    ]
