# Generated by Django 2.0.6 on 2018-07-05 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dostbook', '0011_profpic_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profpic',
            name='status',
            field=models.IntegerField(default=1),
        ),
    ]
