# Generated by Django 2.0.6 on 2018-07-05 18:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dostbook', '0013_auto_20180705_1811'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profpic',
            name='status',
        ),
    ]
