# Generated by Django 2.0.6 on 2018-07-05 18:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dostbook', '0015_auto_20180705_1816'),
    ]

    operations = [
        migrations.DeleteModel(
            name='profpic',
        ),
    ]
