# Generated by Django 2.0.6 on 2018-07-05 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dostbook', '0016_delete_profpic'),
    ]

    operations = [
        migrations.CreateModel(
            name='profpic',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('emailid', models.CharField(max_length=50)),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='profile_picture/%y%m%d')),
            ],
        ),
    ]
