# Generated by Django 2.0.6 on 2018-07-05 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dostbook', '0017_profpic'),
    ]

    operations = [
        migrations.AddField(
            model_name='profpic',
            name='status',
            field=models.IntegerField(default='0'),
        ),
    ]
