# Generated by Django 2.0.6 on 2018-07-13 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dostbook', '0018_profpic_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='post_picture',
            field=models.ImageField(blank=True, null=True, upload_to='post_picture/%y%m%d'),
        ),
    ]
