# Generated by Django 2.0.6 on 2018-07-13 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dostbook', '0019_post_post_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post_picture',
            field=models.ImageField(null=True, upload_to='post_picture/%y%m%d'),
        ),
    ]
