# Generated by Django 2.0.6 on 2018-07-13 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dostbook', '0020_auto_20180713_1127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post_picture',
            field=models.ImageField(blank=True, null=True, upload_to='post_picture/%y%m%d'),
        ),
    ]
