# Generated by Django 2.0.6 on 2018-07-14 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dostbook', '0021_auto_20180713_1135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='msg',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='post_picture',
            field=models.ImageField(null=True, upload_to='post_picture/%y%m%d'),
        ),
    ]
